global:
  resolve_timeout: 5m
  smtp_smarthost: "localhost:25"
  smtp_from: "alertmanager@example.org"

route:
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: "web.hook"

receivers:
- name: "web.hook"
  webhook_configs:
  - url: "http://127.0.0.1:5001/"
