stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw/
    outs:
    - data/processed/
    
  train_models:
    cmd: python scripts/train_models.py
    deps:
    - scripts/train_models.py
    - data/processed/
    outs:
    - models/best_model.joblib
    - models/model_metadata.json
    params:
    - params.yaml:train_params
    
  validate_model:
    cmd: python scripts/validate_model.py
    deps:
    - scripts/validate_model.py
    - models/best_model.joblib
    - data/processed/
    metrics:
    - metrics.json
    
  check_drift:
    cmd: python scripts/check_model_drift.py
    deps:
    - scripts/check_model_drift.py
    - models/best_model.joblib
    - data/processed/
    outs:
    - reports/drift_report.json