stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    outs:
    - data/raw/california_housing_raw.csv
    - data/processed/train_data.csv
    - data/processed/test_data.csv
    - models/scaler.joblib
    
  model_training:
    cmd: python scripts/train_models.py
    deps:
    - src/model_training.py
    - data/processed/train_data.csv
    - data/processed/test_data.csv
    - models/scaler.joblib
    params:
    - model_params
    outs:
    - models/best_model.joblib
    metrics:
    - metrics.json
