train_params:
  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 5
    random_state: 42
  
  linear_regression:
    fit_intercept: true
    normalize: false
  
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state: 42

data_params:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
