model_params:
  linear_regression:
    fit_intercept: true
    
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
    
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 6
    random_state: 42
    
  svr:
    C: 1.0
    epsilon: 0.1
    kernel: rbf

train_test_split:
  test_size: 0.2
  random_state: 42

preprocessing:
  scale_features: true
