global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'california-housing-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 4s
    scheme: http
    honor_labels: true
    scrape_offset: 2s
    metrics_path: '/metrics'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^mlflow_.*'
        action: keep

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
